language: python
python:
  - "3.4"
before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
install:
  - pip install -r requirements.txt
script:
  - npm run build
after_success:
  - npm run publish
notifications:
  email:
    - carriere.denis@gmail.com
