site_name: DLCSPM
site_description: Documentation for DLCSPM
site_author: DLCSPM
site_favicon: favicon.ico
site_url: https://docs.dlcspm.com

repo_url: https://github.com/dlcspm/documentation
repo_name: Documentation

theme: readthedocs
markdown_extensions:
    - smarty
pages:
  - Home: index.md
  - USER DOCUMENTATION:
    - OGC: USER/ogc.md
  - SERVER DOCUMENTATION:
    - GeoServer: SERVER/geoserver.md
    - Security: SERVER/security.md
  - LESSONS LEARNED:
    - CWIX: LESSONS/cwix.md
