site_name: My Docs
site_favicon: favicon.ico
site_url: https://docs.dlcspm.com
repo_url: https://github.com/dlcspm/documentation
site_description: Documentation for DLCSPM
site_author: DLCSPM
theme: readthedocs
markdown_extensions:
  - smarty
pages:
  - Home: index.md
  - Install: install.md
  - CWIX: cwix.md
  - OGC: ogc.md
