site_name: DLCSPM
site_description: Documentation for DLCSPM
site_author: DLCSPM
site_favicon: favicon.ico
site_url: https://docs.dlcspm.com

repo_url: https://github.com/dlcspm/documentation
repo_name: Documentation

theme: readthedocs

pages:
    - Home: index.md
    - Install: install.md
    - User Guides:
      - CWIX: cwix.md
      - OGC: ogc.md
