site_name: DLCSPM
site_description: Documentation for DLCSPM
site_author: DLCSPM
site_favicon: favicon.ico
site_url: https://docs.dlcspm.com

repo_url: https://github.com/dlcspm/documentation
repo_name: Documentation

theme: readthedocs
markdown_extensions:
    - smarty
pages:
  - Home: index.md
  - USER DOCUMENTATION:
    - Security: security.md
    - OGC: ogc.md
  - SERVER DOCUMENTATION:
    - GeoServer: geoserver/README.md
